# Generated by Django 5.2.13 on 2026-05-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="code",
            new_name="isoa3_code",
        ),
        migrations.AlterField(
            model_name="statement",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
