# Generated by Django 5.2.13 on 2026-05-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_code_country_isoa3_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="statement",
            old_name="date",
            new_name="publish_date",
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
