# Generated by Django 5.2.13 on 2026-05-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_date_event_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="full_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="isoa2_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
