# Generated by Django 5.2.13 on 2026-05-12 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_country_full_name_country_isoa2_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statement",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statement",
            name="topics",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="country",
            name="isoa2_code",
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.CreateModel(
            name="RawPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(choices=[("twitter", "Twitter/X")], max_length=50),
                ),
                ("account_handle", models.CharField(max_length=255)),
                ("post_id", models.CharField(max_length=255, unique=True)),
                ("post_text", models.TextField(blank=True)),
                ("image_text", models.TextField(blank=True)),
                ("combined_text", models.TextField(blank=True)),
                ("media_urls", models.JSONField(default=list)),
                ("posted_at", models.DateTimeField()),
                ("post_url", models.URLField()),
                ("ocr_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.country"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="statement",
            name="raw_post",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.rawpost",
            ),
        ),
    ]
