# Generated by Django 5.2.13 on 2026-05-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_statement_confidence_score_statement_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawpost",
            name="image_urls",
            field=models.JSONField(default=list),
        ),
    ]
