# Generated by Django 5.2.13 on 2026-05-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rawpost_image_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawpost",
            name="classify_ai_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rawpost",
            name="content_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="rawpost",
            name="language",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="rawpost",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawpost",
            name="title",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="rawpost",
            name="account_handle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="rawpost",
            name="platform",
            field=models.CharField(
                choices=[
                    ("twitter", "Twitter/X"),
                    ("web", "Web Scrape"),
                    ("pdf", "PDF Document"),
                    ("javascript", "JS Page"),
                ],
                max_length=50,
            ),
        ),
    ]
