# Generated by Django 5.2.13 on 2026-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rawpost_classify_ai_processed_rawpost_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawpost",
            name="post_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="rawpost",
            name="source_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
