# Generated by Django 5.2.13 on 2026-05-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_rawpost_post_url_alter_rawpost_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
