# Generated by Django 5.2.13 on 2026-05-14 11:52

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_country_id"),
    ]

    operations = operations = [
        VectorExtension(),  # runs: CREATE EXTENSION IF NOT EXISTS vector;
    ]
