# Generated by Django 5.2.13 on 2026-05-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_statementchunk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
